/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface BatchRequestOutputResponse { 
    /**
     * The HTTP status code of the response
     */
    statusCode?: number;
    /**
     * An unique identifier for the OpenAI API request. Please include this request ID when contacting support.
     */
    requestId?: string;
    /**
     * The JSON body of the response
     */
    body?: any;
}