/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ChatCompletionResponseMessage } from './chatCompletionResponseMessage';

export interface CreateChatCompletionFunctionResponseChoices { 
    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence, `length` if the maximum number of tokens specified in the request was reached, `content_filter` if content was omitted due to a flag from our content filters, or `function_call` if the model called a function. 
     */
    finishReason: CreateChatCompletionFunctionResponseChoices.FinishReasonEnum;
    /**
     * The index of the choice in the list of choices.
     */
    index: number;
    message: ChatCompletionResponseMessage;
}
export namespace CreateChatCompletionFunctionResponseChoices {
    export type FinishReasonEnum = 'stop' | 'length' | 'function_call' | 'content_filter';
    export const FinishReasonEnum = {
        Stop: 'stop' as FinishReasonEnum,
        Length: 'length' as FinishReasonEnum,
        FunctionCall: 'function_call' as FinishReasonEnum,
        ContentFilter: 'content_filter' as FinishReasonEnum
    };
}