/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The usage information for the request.
 */
export interface CreateEmbeddingResponseUsage { 
    /**
     * The number of tokens used by the prompt.
     */
    promptTokens: number;
    /**
     * The total number of tokens used by the request.
     */
    totalTokens: number;
}