/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DeleteVectorStoreResponse { 
    id: string;
    deleted: boolean;
    object: DeleteVectorStoreResponse.ObjectEnum;
}
export namespace DeleteVectorStoreResponse {
    export type ObjectEnum = 'vector_store.deleted';
    export const ObjectEnum = {
        VectorStoreDeleted: 'vector_store.deleted' as ObjectEnum
    };
}