/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageContentImageFileObject } from './messageContentImageFileObject';
import { MessageContentImageUrlObject } from './messageContentImageUrlObject';
import { MessageContentTextObject } from './messageContentTextObject';
import { MessageObjectAttachments } from './messageObjectAttachments';
import { MessageObjectIncompleteDetails } from './messageObjectIncompleteDetails';

/**
 * Represents a message within a [thread](/docs/api-reference/threads).
 */
export interface MessageObject { 
    /**
     * The identifier, which can be referenced in API endpoints.
     */
    id: string;
    /**
     * The object type, which is always `thread.message`.
     */
    object: MessageObject.ObjectEnum;
    /**
     * The Unix timestamp (in seconds) for when the message was created.
     */
    createdAt: number;
    /**
     * The [thread](/docs/api-reference/threads) ID that this message belongs to.
     */
    threadId: string;
    /**
     * The status of the message, which can be either `in_progress`, `incomplete`, or `completed`.
     */
    status: MessageObject.StatusEnum;
    incompleteDetails: MessageObjectIncompleteDetails;
    /**
     * The Unix timestamp (in seconds) for when the message was completed.
     */
    completedAt: number;
    /**
     * The Unix timestamp (in seconds) for when the message was marked as incomplete.
     */
    incompleteAt: number;
    /**
     * The entity that produced the message. One of `user` or `assistant`.
     */
    role: MessageObject.RoleEnum;
    /**
     * The content of the message in array of text and/or images.
     */
    content: Array<MessageContentImageFileObject | MessageContentImageUrlObject | MessageContentTextObject>;
    /**
     * If applicable, the ID of the [assistant](/docs/api-reference/assistants) that authored this message.
     */
    assistantId: string;
    /**
     * The ID of the [run](/docs/api-reference/runs) associated with the creation of this message. Value is `null` when messages are created manually using the create message or create thread endpoints.
     */
    runId: string;
    /**
     * A list of files attached to the message, and the tools they were added to.
     */
    attachments: Array<MessageObjectAttachments>;
    /**
     * Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long. 
     */
    metadata: any;
}
export namespace MessageObject {
    export type ObjectEnum = 'thread.message';
    export const ObjectEnum = {
        ThreadMessage: 'thread.message' as ObjectEnum
    };
    export type StatusEnum = 'in_progress' | 'incomplete' | 'completed';
    export const StatusEnum = {
        InProgress: 'in_progress' as StatusEnum,
        Incomplete: 'incomplete' as StatusEnum,
        Completed: 'completed' as StatusEnum
    };
    export type RoleEnum = 'user' | 'assistant';
    export const RoleEnum = {
        User: 'user' as RoleEnum,
        Assistant: 'assistant' as RoleEnum
    };
}