/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MessageDeltaContentImageUrlObjectImageUrl { 
    /**
     * The URL of the image, must be a supported image types: jpeg, jpg, png, gif, webp.
     */
    url?: string;
    /**
     * Specifies the detail level of the image. `low` uses fewer tokens, you can opt in to high resolution using `high`.
     */
    detail?: MessageDeltaContentImageUrlObjectImageUrl.DetailEnum;
}
export namespace MessageDeltaContentImageUrlObjectImageUrl {
    export type DetailEnum = 'auto' | 'low' | 'high';
    export const DetailEnum = {
        Auto: 'auto' as DetailEnum,
        Low: 'low' as DetailEnum,
        High: 'high' as DetailEnum
    };
}