/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * On an incomplete message, details about why the message is incomplete.
 */
export interface MessageObjectIncompleteDetails { 
    /**
     * The reason the message is incomplete.
     */
    reason: MessageObjectIncompleteDetails.ReasonEnum;
}
export namespace MessageObjectIncompleteDetails {
    export type ReasonEnum = 'content_filter' | 'max_tokens' | 'run_cancelled' | 'run_expired' | 'run_failed';
    export const ReasonEnum = {
        ContentFilter: 'content_filter' as ReasonEnum,
        MaxTokens: 'max_tokens' as ReasonEnum,
        RunCancelled: 'run_cancelled' as ReasonEnum,
        RunExpired: 'run_expired' as ReasonEnum,
        RunFailed: 'run_failed' as ReasonEnum
    };
}