/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MessageContentTextAnnotationsFileCitationObjectFileCitation } from './messageContentTextAnnotationsFileCitationObjectFileCitation';

/**
 * A citation within the message that points to a specific quote from a specific File associated with the assistant or the message. Generated when the assistant uses the \"file_search\" tool to search files.
 */
export interface MessageContentTextAnnotationsFileCitationObject { 
    /**
     * Always `file_citation`.
     */
    type: MessageContentTextAnnotationsFileCitationObject.TypeEnum;
    /**
     * The text in the message content that needs to be replaced.
     */
    text: string;
    fileCitation: MessageContentTextAnnotationsFileCitationObjectFileCitation;
    startIndex: number;
    endIndex: number;
}
export namespace MessageContentTextAnnotationsFileCitationObject {
    export type TypeEnum = 'file_citation';
    export const TypeEnum = {
        FileCitation: 'file_citation' as TypeEnum
    };
}