/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RunStepDeltaObjectDelta } from './runStepDeltaObjectDelta';

/**
 * Represents a run step delta i.e. any changed fields on a run step during streaming. 
 */
export interface RunStepDeltaObject { 
    /**
     * The identifier of the run step, which can be referenced in API endpoints.
     */
    id: string;
    /**
     * The object type, which is always `thread.run.step.delta`.
     */
    object: RunStepDeltaObject.ObjectEnum;
    delta: RunStepDeltaObjectDelta;
}
export namespace RunStepDeltaObject {
    export type ObjectEnum = 'thread.run.step.delta';
    export const ObjectEnum = {
        ThreadRunStepDelta: 'thread.run.step.delta' as ObjectEnum
    };
}