/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RunStepDetailsToolCallsFunctionObjectFunction } from './runStepDetailsToolCallsFunctionObjectFunction';

export interface RunStepDetailsToolCallsFunctionObject { 
    /**
     * The ID of the tool call object.
     */
    id: string;
    /**
     * The type of tool call. This is always going to be `function` for this type of tool call.
     */
    type: RunStepDetailsToolCallsFunctionObject.TypeEnum;
    _function: RunStepDetailsToolCallsFunctionObjectFunction;
}
export namespace RunStepDetailsToolCallsFunctionObject {
    export type TypeEnum = 'function';
    export const TypeEnum = {
        Function: 'function' as TypeEnum
    };
}