/**
 * OpenAI API
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Controls for how a thread will be truncated prior to the run. Use this to control the intial context window of the run.
 */
export interface TruncationObject { 
    /**
     * The truncation strategy to use for the thread. The default is `auto`. If set to `last_messages`, the thread will be truncated to the n most recent messages in the thread. When set to `auto`, messages in the middle of the thread will be dropped to fit the context length of the model, `max_prompt_tokens`.
     */
    type: TruncationObject.TypeEnum;
    /**
     * The number of most recent messages from the thread when constructing the context for the run.
     */
    lastMessages?: number;
}
export namespace TruncationObject {
    export type TypeEnum = 'auto' | 'last_messages';
    export const TypeEnum = {
        Auto: 'auto' as TypeEnum,
        LastMessages: 'last_messages' as TypeEnum
    };
}