# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.moderations_api import ModerationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModerationsApi(unittest.TestCase):
    """ModerationsApi unit test stubs"""

    def setUp(self):
        self.api = ModerationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_moderation(self):
        """Test case for create_moderation

        Classifies if text is potentially harmful.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
