# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.chat_completion_functions import ChatCompletionFunctions  # noqa: E501
from swagger_client.rest import ApiException


class TestChatCompletionFunctions(unittest.TestCase):
    """ChatCompletionFunctions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatCompletionFunctions(self):
        """Test ChatCompletionFunctions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.chat_completion_functions.ChatCompletionFunctions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
