# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.batch_api import BatchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBatchApi(unittest.TestCase):
    """BatchApi unit test stubs"""

    def setUp(self):
        self.api = BatchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_batch(self):
        """Test case for cancel_batch

        Cancels an in-progress batch.  # noqa: E501
        """
        pass

    def test_create_batch(self):
        """Test case for create_batch

        Creates and executes a batch from an uploaded file of requests  # noqa: E501
        """
        pass

    def test_list_batches(self):
        """Test case for list_batches

        List your organization's batches.  # noqa: E501
        """
        pass

    def test_retrieve_batch(self):
        """Test case for retrieve_batch

        Retrieves a batch.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
