# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.files_api import FilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self):
        self.api = FilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_file(self):
        """Test case for create_file

        Upload a file that can be used across various endpoints. Individual files can be up to 512 MB, and the size of all files uploaded by one organization can be up to 100 GB.  The Assistants API supports files up to 2 million tokens and of specific file types. See the [Assistants Tools guide](/docs/assistants/tools) for details.  The Fine-tuning API only supports `.jsonl` files.  The Batch API only supports `.jsonl` files up to 100 MB in size.  Please [contact us](https://help.openai.com/) if you need to increase these storage limits.   # noqa: E501
        """
        pass

    def test_delete_file(self):
        """Test case for delete_file

        Delete a file.  # noqa: E501
        """
        pass

    def test_download_file(self):
        """Test case for download_file

        Returns the contents of the specified file.  # noqa: E501
        """
        pass

    def test_list_files(self):
        """Test case for list_files

        Returns a list of files that belong to the user's organization.  # noqa: E501
        """
        pass

    def test_retrieve_file(self):
        """Test case for retrieve_file

        Returns information about a specific file.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
