# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_create_message_request_content import OneOfCreateMessageRequestContent  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfCreateMessageRequestContent(unittest.TestCase):
    """OneOfCreateMessageRequestContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfCreateMessageRequestContent(self):
        """Test OneOfCreateMessageRequestContent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_create_message_request_content.OneOfCreateMessageRequestContent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
