# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_run_step_details_tool_calls_object_tool_calls_items import OneOfRunStepDetailsToolCallsObjectToolCallsItems  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfRunStepDetailsToolCallsObjectToolCallsItems(unittest.TestCase):
    """OneOfRunStepDetailsToolCallsObjectToolCallsItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfRunStepDetailsToolCallsObjectToolCallsItems(self):
        """Test OneOfRunStepDetailsToolCallsObjectToolCallsItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_run_step_details_tool_calls_object_tool_calls_items.OneOfRunStepDetailsToolCallsObjectToolCallsItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
