# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.audio_api import AudioApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAudioApi(unittest.TestCase):
    """AudioApi unit test stubs"""

    def setUp(self):
        self.api = AudioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_speech(self):
        """Test case for create_speech

        Generates audio from the input text.  # noqa: E501
        """
        pass

    def test_create_transcription(self):
        """Test case for create_transcription

        Transcribes audio into the input language.  # noqa: E501
        """
        pass

    def test_create_translation(self):
        """Test case for create_translation

        Translates audio into English.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
