# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_vector_stores_response import ListVectorStoresResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestListVectorStoresResponse(unittest.TestCase):
    """ListVectorStoresResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListVectorStoresResponse(self):
        """Test ListVectorStoresResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_vector_stores_response.ListVectorStoresResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
