export * from './aPIGatewayLoginServiceAuthInfo.service';
import { APIGatewayLoginServiceAuthInfoService } from './aPIGatewayLoginServiceAuthInfo.service';
export * from './aPIGatewayLoginServiceAuthenticate.service';
import { APIGatewayLoginServiceAuthenticateService } from './aPIGatewayLoginServiceAuthenticate.service';
export * from './aPIGatewayLoginServiceCreateInviteusers.service';
import { APIGatewayLoginServiceCreateInviteusersService } from './aPIGatewayLoginServiceCreateInviteusers.service';
export * from './aPIGatewayLoginServiceGateway.service';
import { APIGatewayLoginServiceGatewayService } from './aPIGatewayLoginServiceGateway.service';
export * from './aPIGatewayLoginServiceGetAuthorities.service';
import { APIGatewayLoginServiceGetAuthoritiesService } from './aPIGatewayLoginServiceGetAuthorities.service';
export * from './aPIGatewayLoginServiceGetInviteusers.service';
import { APIGatewayLoginServiceGetInviteusersService } from './aPIGatewayLoginServiceGetInviteusers.service';
export * from './aPIGatewayLoginServiceGetUsers.service';
import { APIGatewayLoginServiceGetUsersService } from './aPIGatewayLoginServiceGetUsers.service';
export * from './aPIGatewayLoginServiceLoginUser.service';
import { APIGatewayLoginServiceLoginUserService } from './aPIGatewayLoginServiceLoginUser.service';
export * from './aPIGatewayManagementServiceAdminApproveAdvs.service';
import { APIGatewayManagementServiceAdminApproveAdvsService } from './aPIGatewayManagementServiceAdminApproveAdvs.service';
export * from './aPIGatewayManagementServiceAdminCreateAdvsForUser.service';
import { APIGatewayManagementServiceAdminCreateAdvsForUserService } from './aPIGatewayManagementServiceAdminCreateAdvsForUser.service';
export * from './aPIGatewayManagementServiceAdminDeleteAdvsById.service';
import { APIGatewayManagementServiceAdminDeleteAdvsByIdService } from './aPIGatewayManagementServiceAdminDeleteAdvsById.service';
export * from './aPIGatewayManagementServiceAdminGetAdvsById.service';
import { APIGatewayManagementServiceAdminGetAdvsByIdService } from './aPIGatewayManagementServiceAdminGetAdvsById.service';
export * from './aPIGatewayManagementServiceAdminGetAllAdvs.service';
import { APIGatewayManagementServiceAdminGetAllAdvsService } from './aPIGatewayManagementServiceAdminGetAllAdvs.service';
export * from './aPIGatewayManagementServiceAdminRejectAdvs.service';
import { APIGatewayManagementServiceAdminRejectAdvsService } from './aPIGatewayManagementServiceAdminRejectAdvs.service';
export * from './aPIGatewayManagementServiceAdminUpdateAdvsById.service';
import { APIGatewayManagementServiceAdminUpdateAdvsByIdService } from './aPIGatewayManagementServiceAdminUpdateAdvsById.service';
export * from './aPIGatewayManagementServiceUserGetAdv.service';
import { APIGatewayManagementServiceUserGetAdvService } from './aPIGatewayManagementServiceUserGetAdv.service';
export * from './aPIGatewayManagementServiceUserGetAllAdvs.service';
import { APIGatewayManagementServiceUserGetAllAdvsService } from './aPIGatewayManagementServiceUserGetAllAdvs.service';
export * from './aPIGatewayUserServiceLoginAdmin.service';
import { APIGatewayUserServiceLoginAdminService } from './aPIGatewayUserServiceLoginAdmin.service';
export * from './aPIGatewayUserServiceSignUpAdmin.service';
import { APIGatewayUserServiceSignUpAdminService } from './aPIGatewayUserServiceSignUpAdmin.service';
export * from './aPIGatewayUserServiceUserInfo.service';
import { APIGatewayUserServiceUserInfoService } from './aPIGatewayUserServiceUserInfo.service';
export const APIS = [APIGatewayLoginServiceAuthInfoService, APIGatewayLoginServiceAuthenticateService, APIGatewayLoginServiceCreateInviteusersService, APIGatewayLoginServiceGatewayService, APIGatewayLoginServiceGetAuthoritiesService, APIGatewayLoginServiceGetInviteusersService, APIGatewayLoginServiceGetUsersService, APIGatewayLoginServiceLoginUserService, APIGatewayManagementServiceAdminApproveAdvsService, APIGatewayManagementServiceAdminCreateAdvsForUserService, APIGatewayManagementServiceAdminDeleteAdvsByIdService, APIGatewayManagementServiceAdminGetAdvsByIdService, APIGatewayManagementServiceAdminGetAllAdvsService, APIGatewayManagementServiceAdminRejectAdvsService, APIGatewayManagementServiceAdminUpdateAdvsByIdService, APIGatewayManagementServiceUserGetAdvService, APIGatewayManagementServiceUserGetAllAdvsService, APIGatewayUserServiceLoginAdminService, APIGatewayUserServiceSignUpAdminService, APIGatewayUserServiceUserInfoService];
