# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssistantObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'object': 'str',
        'created_at': 'int',
        'name': 'str',
        'description': 'str',
        'model': 'str',
        'instructions': 'str',
        'tools': 'list[OneOfAssistantObjectToolsItems]',
        'tool_resources': 'AssistantObjectToolResources',
        'metadata': 'object',
        'temperature': 'float',
        'top_p': 'float',
        'response_format': 'AssistantsApiResponseFormatOption'
    }

    attribute_map = {
        'id': 'id',
        'object': 'object',
        'created_at': 'created_at',
        'name': 'name',
        'description': 'description',
        'model': 'model',
        'instructions': 'instructions',
        'tools': 'tools',
        'tool_resources': 'tool_resources',
        'metadata': 'metadata',
        'temperature': 'temperature',
        'top_p': 'top_p',
        'response_format': 'response_format'
    }

    def __init__(self, id=None, object=None, created_at=None, name=None, description=None, model=None, instructions=None, tools=None, tool_resources=None, metadata=None, temperature=1, top_p=1, response_format=None):  # noqa: E501
        """AssistantObject - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._object = None
        self._created_at = None
        self._name = None
        self._description = None
        self._model = None
        self._instructions = None
        self._tools = None
        self._tool_resources = None
        self._metadata = None
        self._temperature = None
        self._top_p = None
        self._response_format = None
        self.discriminator = None
        self.id = id
        self.object = object
        self.created_at = created_at
        self.name = name
        self.description = description
        self.model = model
        self.instructions = instructions
        self.tools = tools
        if tool_resources is not None:
            self.tool_resources = tool_resources
        self.metadata = metadata
        if temperature is not None:
            self.temperature = temperature
        if top_p is not None:
            self.top_p = top_p
        if response_format is not None:
            self.response_format = response_format

    @property
    def id(self):
        """Gets the id of this AssistantObject.  # noqa: E501

        The identifier, which can be referenced in API endpoints.  # noqa: E501

        :return: The id of this AssistantObject.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AssistantObject.

        The identifier, which can be referenced in API endpoints.  # noqa: E501

        :param id: The id of this AssistantObject.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def object(self):
        """Gets the object of this AssistantObject.  # noqa: E501

        The object type, which is always `assistant`.  # noqa: E501

        :return: The object of this AssistantObject.  # noqa: E501
        :rtype: str
        """
        return self._object

    @object.setter
    def object(self, object):
        """Sets the object of this AssistantObject.

        The object type, which is always `assistant`.  # noqa: E501

        :param object: The object of this AssistantObject.  # noqa: E501
        :type: str
        """
        if object is None:
            raise ValueError("Invalid value for `object`, must not be `None`")  # noqa: E501
        allowed_values = ["assistant"]  # noqa: E501
        if object not in allowed_values:
            raise ValueError(
                "Invalid value for `object` ({0}), must be one of {1}"  # noqa: E501
                .format(object, allowed_values)
            )

        self._object = object

    @property
    def created_at(self):
        """Gets the created_at of this AssistantObject.  # noqa: E501

        The Unix timestamp (in seconds) for when the assistant was created.  # noqa: E501

        :return: The created_at of this AssistantObject.  # noqa: E501
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this AssistantObject.

        The Unix timestamp (in seconds) for when the assistant was created.  # noqa: E501

        :param created_at: The created_at of this AssistantObject.  # noqa: E501
        :type: int
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def name(self):
        """Gets the name of this AssistantObject.  # noqa: E501

        The name of the assistant. The maximum length is 256 characters.   # noqa: E501

        :return: The name of this AssistantObject.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AssistantObject.

        The name of the assistant. The maximum length is 256 characters.   # noqa: E501

        :param name: The name of this AssistantObject.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this AssistantObject.  # noqa: E501

        The description of the assistant. The maximum length is 512 characters.   # noqa: E501

        :return: The description of this AssistantObject.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AssistantObject.

        The description of the assistant. The maximum length is 512 characters.   # noqa: E501

        :param description: The description of this AssistantObject.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def model(self):
        """Gets the model of this AssistantObject.  # noqa: E501

        ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them.   # noqa: E501

        :return: The model of this AssistantObject.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this AssistantObject.

        ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them.   # noqa: E501

        :param model: The model of this AssistantObject.  # noqa: E501
        :type: str
        """
        if model is None:
            raise ValueError("Invalid value for `model`, must not be `None`")  # noqa: E501

        self._model = model

    @property
    def instructions(self):
        """Gets the instructions of this AssistantObject.  # noqa: E501

        The system instructions that the assistant uses. The maximum length is 256,000 characters.   # noqa: E501

        :return: The instructions of this AssistantObject.  # noqa: E501
        :rtype: str
        """
        return self._instructions

    @instructions.setter
    def instructions(self, instructions):
        """Sets the instructions of this AssistantObject.

        The system instructions that the assistant uses. The maximum length is 256,000 characters.   # noqa: E501

        :param instructions: The instructions of this AssistantObject.  # noqa: E501
        :type: str
        """
        if instructions is None:
            raise ValueError("Invalid value for `instructions`, must not be `None`")  # noqa: E501

        self._instructions = instructions

    @property
    def tools(self):
        """Gets the tools of this AssistantObject.  # noqa: E501

        A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types `code_interpreter`, `file_search`, or `function`.   # noqa: E501

        :return: The tools of this AssistantObject.  # noqa: E501
        :rtype: list[OneOfAssistantObjectToolsItems]
        """
        return self._tools

    @tools.setter
    def tools(self, tools):
        """Sets the tools of this AssistantObject.

        A list of tool enabled on the assistant. There can be a maximum of 128 tools per assistant. Tools can be of types `code_interpreter`, `file_search`, or `function`.   # noqa: E501

        :param tools: The tools of this AssistantObject.  # noqa: E501
        :type: list[OneOfAssistantObjectToolsItems]
        """
        if tools is None:
            raise ValueError("Invalid value for `tools`, must not be `None`")  # noqa: E501

        self._tools = tools

    @property
    def tool_resources(self):
        """Gets the tool_resources of this AssistantObject.  # noqa: E501


        :return: The tool_resources of this AssistantObject.  # noqa: E501
        :rtype: AssistantObjectToolResources
        """
        return self._tool_resources

    @tool_resources.setter
    def tool_resources(self, tool_resources):
        """Sets the tool_resources of this AssistantObject.


        :param tool_resources: The tool_resources of this AssistantObject.  # noqa: E501
        :type: AssistantObjectToolResources
        """

        self._tool_resources = tool_resources

    @property
    def metadata(self):
        """Gets the metadata of this AssistantObject.  # noqa: E501

        Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.   # noqa: E501

        :return: The metadata of this AssistantObject.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this AssistantObject.

        Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.   # noqa: E501

        :param metadata: The metadata of this AssistantObject.  # noqa: E501
        :type: object
        """
        if metadata is None:
            raise ValueError("Invalid value for `metadata`, must not be `None`")  # noqa: E501

        self._metadata = metadata

    @property
    def temperature(self):
        """Gets the temperature of this AssistantObject.  # noqa: E501

        What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.   # noqa: E501

        :return: The temperature of this AssistantObject.  # noqa: E501
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this AssistantObject.

        What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.   # noqa: E501

        :param temperature: The temperature of this AssistantObject.  # noqa: E501
        :type: float
        """

        self._temperature = temperature

    @property
    def top_p(self):
        """Gets the top_p of this AssistantObject.  # noqa: E501

        An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or temperature but not both.   # noqa: E501

        :return: The top_p of this AssistantObject.  # noqa: E501
        :rtype: float
        """
        return self._top_p

    @top_p.setter
    def top_p(self, top_p):
        """Sets the top_p of this AssistantObject.

        An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.  We generally recommend altering this or temperature but not both.   # noqa: E501

        :param top_p: The top_p of this AssistantObject.  # noqa: E501
        :type: float
        """

        self._top_p = top_p

    @property
    def response_format(self):
        """Gets the response_format of this AssistantObject.  # noqa: E501


        :return: The response_format of this AssistantObject.  # noqa: E501
        :rtype: AssistantsApiResponseFormatOption
        """
        return self._response_format

    @response_format.setter
    def response_format(self, response_format):
        """Sets the response_format of this AssistantObject.


        :param response_format: The response_format of this AssistantObject.  # noqa: E501
        :type: AssistantsApiResponseFormatOption
        """

        self._response_format = response_format

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssistantObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssistantObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
