# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BatchErrorsData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'message': 'str',
        'param': 'str',
        'line': 'int'
    }

    attribute_map = {
        'code': 'code',
        'message': 'message',
        'param': 'param',
        'line': 'line'
    }

    def __init__(self, code=None, message=None, param=None, line=None):  # noqa: E501
        """BatchErrorsData - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._message = None
        self._param = None
        self._line = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if message is not None:
            self.message = message
        if param is not None:
            self.param = param
        if line is not None:
            self.line = line

    @property
    def code(self):
        """Gets the code of this BatchErrorsData.  # noqa: E501

        An error code identifying the error type.  # noqa: E501

        :return: The code of this BatchErrorsData.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this BatchErrorsData.

        An error code identifying the error type.  # noqa: E501

        :param code: The code of this BatchErrorsData.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def message(self):
        """Gets the message of this BatchErrorsData.  # noqa: E501

        A human-readable message providing more details about the error.  # noqa: E501

        :return: The message of this BatchErrorsData.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this BatchErrorsData.

        A human-readable message providing more details about the error.  # noqa: E501

        :param message: The message of this BatchErrorsData.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def param(self):
        """Gets the param of this BatchErrorsData.  # noqa: E501

        The name of the parameter that caused the error, if applicable.  # noqa: E501

        :return: The param of this BatchErrorsData.  # noqa: E501
        :rtype: str
        """
        return self._param

    @param.setter
    def param(self, param):
        """Sets the param of this BatchErrorsData.

        The name of the parameter that caused the error, if applicable.  # noqa: E501

        :param param: The param of this BatchErrorsData.  # noqa: E501
        :type: str
        """

        self._param = param

    @property
    def line(self):
        """Gets the line of this BatchErrorsData.  # noqa: E501

        The line number of the input file where the error occurred, if applicable.  # noqa: E501

        :return: The line of this BatchErrorsData.  # noqa: E501
        :rtype: int
        """
        return self._line

    @line.setter
    def line(self, line):
        """Sets the line of this BatchErrorsData.

        The line number of the input file where the error occurred, if applicable.  # noqa: E501

        :param line: The line of this BatchErrorsData.  # noqa: E501
        :type: int
        """

        self._line = line

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchErrorsData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchErrorsData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
