# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateThreadRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'messages': 'list[CreateMessageRequest]',
        'tool_resources': 'CreateThreadRequestToolResources',
        'metadata': 'object'
    }

    attribute_map = {
        'messages': 'messages',
        'tool_resources': 'tool_resources',
        'metadata': 'metadata'
    }

    def __init__(self, messages=None, tool_resources=None, metadata=None):  # noqa: E501
        """CreateThreadRequest - a model defined in Swagger"""  # noqa: E501
        self._messages = None
        self._tool_resources = None
        self._metadata = None
        self.discriminator = None
        if messages is not None:
            self.messages = messages
        if tool_resources is not None:
            self.tool_resources = tool_resources
        if metadata is not None:
            self.metadata = metadata

    @property
    def messages(self):
        """Gets the messages of this CreateThreadRequest.  # noqa: E501

        A list of [messages](/docs/api-reference/messages) to start the thread with.  # noqa: E501

        :return: The messages of this CreateThreadRequest.  # noqa: E501
        :rtype: list[CreateMessageRequest]
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this CreateThreadRequest.

        A list of [messages](/docs/api-reference/messages) to start the thread with.  # noqa: E501

        :param messages: The messages of this CreateThreadRequest.  # noqa: E501
        :type: list[CreateMessageRequest]
        """

        self._messages = messages

    @property
    def tool_resources(self):
        """Gets the tool_resources of this CreateThreadRequest.  # noqa: E501


        :return: The tool_resources of this CreateThreadRequest.  # noqa: E501
        :rtype: CreateThreadRequestToolResources
        """
        return self._tool_resources

    @tool_resources.setter
    def tool_resources(self, tool_resources):
        """Sets the tool_resources of this CreateThreadRequest.


        :param tool_resources: The tool_resources of this CreateThreadRequest.  # noqa: E501
        :type: CreateThreadRequestToolResources
        """

        self._tool_resources = tool_resources

    @property
    def metadata(self):
        """Gets the metadata of this CreateThreadRequest.  # noqa: E501

        Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.   # noqa: E501

        :return: The metadata of this CreateThreadRequest.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this CreateThreadRequest.

        Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.   # noqa: E501

        :param metadata: The metadata of this CreateThreadRequest.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateThreadRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateThreadRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
