# coding: utf-8

"""
    OpenAI API

    The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UpdateVectorStoreRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'expires_after': 'VectorStoreExpirationAfter',
        'metadata': 'object'
    }

    attribute_map = {
        'name': 'name',
        'expires_after': 'expires_after',
        'metadata': 'metadata'
    }

    def __init__(self, name=None, expires_after=None, metadata=None):  # noqa: E501
        """UpdateVectorStoreRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._expires_after = None
        self._metadata = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if expires_after is not None:
            self.expires_after = expires_after
        if metadata is not None:
            self.metadata = metadata

    @property
    def name(self):
        """Gets the name of this UpdateVectorStoreRequest.  # noqa: E501

        The name of the vector store.  # noqa: E501

        :return: The name of this UpdateVectorStoreRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdateVectorStoreRequest.

        The name of the vector store.  # noqa: E501

        :param name: The name of this UpdateVectorStoreRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def expires_after(self):
        """Gets the expires_after of this UpdateVectorStoreRequest.  # noqa: E501


        :return: The expires_after of this UpdateVectorStoreRequest.  # noqa: E501
        :rtype: VectorStoreExpirationAfter
        """
        return self._expires_after

    @expires_after.setter
    def expires_after(self, expires_after):
        """Sets the expires_after of this UpdateVectorStoreRequest.


        :param expires_after: The expires_after of this UpdateVectorStoreRequest.  # noqa: E501
        :type: VectorStoreExpirationAfter
        """

        self._expires_after = expires_after

    @property
    def metadata(self):
        """Gets the metadata of this UpdateVectorStoreRequest.  # noqa: E501

        Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.   # noqa: E501

        :return: The metadata of this UpdateVectorStoreRequest.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this UpdateVectorStoreRequest.

        Set of 16 key-value pairs that can be attached to an object. This can be useful for storing additional information about the object in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.   # noqa: E501

        :param metadata: The metadata of this UpdateVectorStoreRequest.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UpdateVectorStoreRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateVectorStoreRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
